spring.application.name=allthings

# criar comunicação com o banco de dados

# url de conexão com o banco (endereço + porta + nome do banco)
spring.datasource.url = jdbc:postgresql://localhost:5432/db_allthings

# usuário d banco de dados
spring.datasource.username = postgres

# senha do banco de dados
spring.datasource.password = postdba

# driver responsável pela conexão com postg
spring.datasource.driver-class-name=org.postgresql.Driver

# define como o hibernate vai gerenciar as tabelas (update= cria/atualiza sem apagar dados)
spring.jpa.hibernate.ddl-auto = update

# mostra no console as consultas sql executadas
spring.jpa.show-sql = true

spring.thymeleaf.cache = false

# formata o sql exibido no console para facilitar leitura
spring.jpa.properties.hibernate.format_sql = true

# define o tipo de banco utilizado (dialeto do postg)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#limitar tamanho maximo do arquivo para 2mb
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
